// <auto-generated />
using System;
using CleanArch.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250906150758_AddPasswordColumn")]
    partial class AddPasswordColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CleanArch.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0aa1efde-c798-40dd-b85c-a4c58cfda446"),
                            CreatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carl.gauss@example",
                            FirstName = "Carl",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Gauss",
                            Password = "6F852F607905CE1E58918A6BE99F793F0DEC1A2938D4BE901519B9D526D0FC57A0062378B42994098AB3F6208E2E8B2021AAB15D40814711701BAF8DDE22EE56-A8CF68410CABDAD5B6DC7B222D523923",
                            UpdatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("60176952-afc2-4cf7-ab94-ad142d343c47"),
                            CreatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "leonhard.euler@example",
                            FirstName = "Leonhard",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Euler",
                            Password = "6F852F607905CE1E58918A6BE99F793F0DEC1A2938D4BE901519B9D526D0FC57A0062378B42994098AB3F6208E2E8B2021AAB15D40814711701BAF8DDE22EE56-A8CF68410CABDAD5B6DC7B222D523923",
                            UpdatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d084a8c1-8d83-473d-8ebd-ea204adb5bfc"),
                            CreatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ada.lovelace@example",
                            FirstName = "Ada",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Lovelace",
                            Password = "6F852F607905CE1E58918A6BE99F793F0DEC1A2938D4BE901519B9D526D0FC57A0062378B42994098AB3F6208E2E8B2021AAB15D40814711701BAF8DDE22EE56-A8CF68410CABDAD5B6DC7B222D523923",
                            UpdatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4e386b6b-1fbb-409f-94f1-5ef10887a3b5"),
                            CreatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.curie@example",
                            FirstName = "Marie",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Curie",
                            Password = "6F852F607905CE1E58918A6BE99F793F0DEC1A2938D4BE901519B9D526D0FC57A0062378B42994098AB3F6208E2E8B2021AAB15D40814711701BAF8DDE22EE56-A8CF68410CABDAD5B6DC7B222D523923",
                            UpdatedAt = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
