// <auto-generated />
using System;
using CleanArch.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250823183609_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CleanArch.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7924816e-af12-4f3e-abdf-ab1e2e613a18"),
                            CreatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(4290),
                            Email = "carl.gauss@example",
                            FirstName = "Carl",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Gauss",
                            UpdatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(4298)
                        },
                        new
                        {
                            Id = new Guid("6d59e76a-eb4d-4957-8734-4111b375fc52"),
                            CreatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(6231),
                            Email = "leonhard.euler@example",
                            FirstName = "Leonhard",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Euler",
                            UpdatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(6233)
                        },
                        new
                        {
                            Id = new Guid("dfaca3cd-b7c1-4d86-9ede-f7ec905178d3"),
                            CreatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(6235),
                            Email = "ada.lovelace@example",
                            FirstName = "Ada",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Lovelace",
                            UpdatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(6236)
                        },
                        new
                        {
                            Id = new Guid("c89afcb4-e59d-4eff-8324-b70de9fdc53a"),
                            CreatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(6237),
                            Email = "marie.curie@example",
                            FirstName = "Marie",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Curie",
                            UpdatedAt = new DateTime(2025, 8, 23, 15, 36, 8, 778, DateTimeKind.Local).AddTicks(6238)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
