// <auto-generated />
using System;
using CleanArch.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CleanArch.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d60a4f9d-5e13-49f7-a7e2-0efe085ab498"),
                            CreatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(516),
                            Email = "carl.gauss@example",
                            FirstName = "Carl",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Gauss",
                            UpdatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(523)
                        },
                        new
                        {
                            Id = new Guid("3ecadbb9-aecf-4419-be72-ed0b7f688633"),
                            CreatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(2462),
                            Email = "leonhard.euler@example",
                            FirstName = "Leonhard",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Euler",
                            UpdatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(2464)
                        },
                        new
                        {
                            Id = new Guid("313d1efc-5e21-4506-97b3-48e12414cb99"),
                            CreatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(2467),
                            Email = "ada.lovelace@example",
                            FirstName = "Ada",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Lovelace",
                            UpdatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(2468)
                        },
                        new
                        {
                            Id = new Guid("e2dc76d9-67b2-4331-b96a-7b49283a0775"),
                            CreatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(2469),
                            Email = "marie.curie@example",
                            FirstName = "Marie",
                            Gender = "Female",
                            IsActive = true,
                            LastName = "Curie",
                            UpdatedAt = new DateTime(2025, 9, 1, 22, 7, 14, 658, DateTimeKind.Local).AddTicks(2470)
                        });
                });            
#pragma warning restore 612, 618
        }
    }
}
